/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg360;

import com.google.gson.Gson;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Arrays;

/**
 *
 * @author cdbitesky
 */
public class leaderBoardFrame extends javax.swing.JFrame {

    /**
     * Creates new form leaderBoardFrame
     */
    public leaderBoardFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelPlayer1 = new javax.swing.JLabel();
        labelScore1 = new javax.swing.JLabel();
        labelPlayer2 = new javax.swing.JLabel();
        labelScore2 = new javax.swing.JLabel();
        labelPlayer3 = new javax.swing.JLabel();
        labelScore3 = new javax.swing.JLabel();
        labelPlayer4 = new javax.swing.JLabel();
        labelScore4 = new javax.swing.JLabel();
        buttonClose = new javax.swing.JButton();

        setTitle("Top Scores");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Player:");

        jLabel2.setText("Score:");

        labelPlayer1.setText("Player1");

        labelScore1.setText("Score1");

        labelPlayer2.setText("Player2");

        labelScore2.setText("Score2");

        labelPlayer3.setText("Player3");

        labelScore3.setText("Score3");

        labelPlayer4.setText("Player4");

        labelScore4.setText("Score4");

        buttonClose.setText("Close");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPlayer1)
                            .addComponent(labelPlayer2)
                            .addComponent(labelPlayer3)
                            .addComponent(labelPlayer4)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelScore4)
                            .addComponent(labelScore3)
                            .addComponent(labelScore2)
                            .addComponent(labelScore1)
                            .addComponent(jLabel2))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelScore1)
                    .addComponent(labelPlayer1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlayer2)
                    .addComponent(labelScore2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelScore3)
                    .addComponent(labelPlayer3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelScore4)
                    .addComponent(labelPlayer4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String line = "";
        Gson gson = new Gson();
        
        try {
            File f = new File("top_scores.txt");
            if(f.exists()) {
                BufferedReader reader = 
                    new BufferedReader( 
                        new FileReader("top_scores.txt") );
                line = reader.readLine();
                //System.out.println("^"+line+"^");
            }
            else {
                Score[] t = {new Score(0, 0)};
                line = gson.toJson(t);
            }
        }
        catch( Exception e ) {
            System.out.println("Exceptione is ="+e.getMessage());
        }
        Score[] scoreList = gson.fromJson(line, Score[].class);
        if( scoreList.length < 4 ) {
            int tmp = scoreList.length - 1;
            Main.expand(scoreList, 4);
            for (int i = tmp; i < 4; i++) {
                scoreList[i] = new Score(0, 0);
            }
        }
        Score[] top5 = new Score[4];
        Arrays.sort(scoreList);
        System.arraycopy(scoreList, 0, top5, 0, 4);
        {
            labelPlayer1.setText(top5[0].sName); labelScore1.setText(""+top5[0].uScore);
            labelPlayer2.setText(top5[1].sName); labelScore2.setText(""+top5[1].uScore);
            labelPlayer3.setText(top5[2].sName); labelScore3.setText(""+top5[2].uScore);
            labelPlayer4.setText(top5[3].sName); labelScore4.setText(""+top5[3].uScore);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leaderBoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leaderBoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leaderBoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leaderBoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new leaderBoardFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelPlayer1;
    private javax.swing.JLabel labelPlayer2;
    private javax.swing.JLabel labelPlayer3;
    private javax.swing.JLabel labelPlayer4;
    private javax.swing.JLabel labelScore1;
    private javax.swing.JLabel labelScore2;
    private javax.swing.JLabel labelScore3;
    private javax.swing.JLabel labelScore4;
    // End of variables declaration//GEN-END:variables
}
