package pkg360;

import com.google.gson.Gson;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.text.Format;
import java.text.SimpleDateFormat;

/**
 * @author Caleb Morris
 */
public class playerStatsFrame extends javax.swing.JFrame {

    /**
     * Creates new form playerStatsFrame
     */
    public playerStatsFrame() {
        initComponents();
        UserData d = UserData.getInstance();
        setTitle("Player Statistics - " + d.uName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelTime1 = new javax.swing.JLabel();
        labelScore1 = new javax.swing.JLabel();
        labelDate1 = new javax.swing.JLabel();
        labelTime2 = new javax.swing.JLabel();
        labelScore2 = new javax.swing.JLabel();
        labelDate2 = new javax.swing.JLabel();
        labelTime3 = new javax.swing.JLabel();
        labelScore3 = new javax.swing.JLabel();
        labelDate3 = new javax.swing.JLabel();
        lNumGamesl = new javax.swing.JLabel();
        lTopScorel = new javax.swing.JLabel();
        labelTopScore = new javax.swing.JLabel();
        labelTotalGames = new javax.swing.JLabel();

        setTitle("Player Statistics");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Date/Time:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Score:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Completion Time:");

        lNumGamesl.setText("Total Games Played: ");

        lTopScorel.setText("Top Score:");

        labelTopScore.setText("421");

        labelTotalGames.setText("42");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lTopScorel)
                        .addGap(18, 18, 18)
                        .addComponent(labelTopScore, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lNumGamesl)
                        .addGap(18, 18, 18)
                        .addComponent(labelTotalGames, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(labelDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelDate3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelScore1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelScore2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelScore3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTime1)
                                    .addComponent(labelTime2)
                                    .addComponent(labelTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(labelScore1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDate2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelScore2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTime2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDate3, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTime3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelScore3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTopScorel)
                    .addComponent(lNumGamesl)
                    .addComponent(labelTopScore)
                    .addComponent(labelTotalGames))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO LOW PRIORITY
        // BUG: infinite scoreboxs
        String line = "";
        Gson gson = new Gson();
        try {
            File f = new File("scores.txt");
            if(f.exists()) {
                BufferedReader reader = 
                    new BufferedReader( 
                        new FileReader("scores.txt") );
                line = reader.readLine();
                //System.out.println("^"+line+"^");
            }
            else {
                Score[] t = null;
                line = gson.toJson(t);
            }
            Score[] scoreList = gson.fromJson(line, Score[].class);
            if( scoreList != null ) {
                Format formatter = new SimpleDateFormat("MM/dd/yy HH:mm");
                //String s = formatter.format(date);
                //System.out.println(s);
                
                Score top = scoreList[0];
                for (int i = 0; i < scoreList.length; i++) {
                    System.out.println( scoreList[i].sName + " "+ scoreList[i].uScore );
                    if( scoreList[i].uScore > top.uScore )
                        top = scoreList[i];
                }
                labelTotalGames.setText(""+scoreList.length);
                labelTopScore.setText(""+top.uScore);
                if( scoreList.length >= 3 ) {
                    labelDate1.setText(formatter.format(scoreList[scoreList.length-3].date));
                    labelScore1.setText(""+scoreList[scoreList.length-3].uScore);
                    labelTime1.setText(""+scoreList[scoreList.length-3].endtime);
                    labelDate2.setText(formatter.format(scoreList[scoreList.length-2].date));
                    labelScore2.setText(""+scoreList[scoreList.length-2].uScore);
                    labelTime2.setText(""+scoreList[scoreList.length-2].endtime);
                    labelDate3.setText(formatter.format(scoreList[scoreList.length-1].date));
                    labelScore3.setText(""+scoreList[scoreList.length-1].uScore);
                    labelTime3.setText(""+scoreList[scoreList.length-1].endtime);
                }
                else if( scoreList.length == 2 ) {
                    labelDate1.setText(formatter.format(scoreList[0].date));
                    labelScore1.setText(""+scoreList[0].uScore);
                    labelTime1.setText(""+scoreList[0].endtime);
                    labelDate2.setText(formatter.format(scoreList[1].date));
                    labelScore2.setText(""+scoreList[1].uScore);
                    labelTime1.setText(""+scoreList[1].endtime);
                }
                else {
                    labelDate1.setText(formatter.format(scoreList[0].date));
                    labelScore1.setText(""+scoreList[0].uScore);
                    labelTime1.setText(""+scoreList[0].endtime);
                }
            }
            else{
                System.out.println("No scores.");
                labelScore2.setText("You have not played any games.");
                labelTopScore.setText(""+0);
                labelTotalGames.setText(""+0);
            }
        }
        catch( Exception e ) {
            System.out.println("Exceptione is ="+e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playerStatsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playerStatsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playerStatsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playerStatsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new playerStatsFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lNumGamesl;
    private javax.swing.JLabel lTopScorel;
    private javax.swing.JLabel labelDate1;
    private javax.swing.JLabel labelDate2;
    private javax.swing.JLabel labelDate3;
    private javax.swing.JLabel labelScore1;
    private javax.swing.JLabel labelScore2;
    private javax.swing.JLabel labelScore3;
    private javax.swing.JLabel labelTime1;
    private javax.swing.JLabel labelTime2;
    private javax.swing.JLabel labelTime3;
    private javax.swing.JLabel labelTopScore;
    private javax.swing.JLabel labelTotalGames;
    // End of variables declaration//GEN-END:variables
}
